version: '3'
services:
  api:
    container_name: node-clear-archetecture-ioc
    build:
      context: './'
      dockerfile: ./docker/api.dockerfile
    restart: always
    depends_on:
      - db
    volumes:
      - ./:/var/www/app
    ports:
      - 3003:3003
    networks:
      - mynetwork
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork
    ports:
      - "5432:5432"
networks:
  mynetwork:
volumes:
  postgres-data:
